# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'project-bnb321' do
pod 'EZAudio', '~> 1.1.4'
end

target 'project-bnb321Tests' do

end

target 'project-bnb321UITests' do

end

